/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.binhgiunhiet_g3.view;

import com.binhgiunhiet_g3.entity.KhuyenMai;
import com.binhgiunhiet_g3.service.KhuyenMaiService;
import com.binhgiunhiet_g3.service.impl.KhuyenMaiServiceImpl;
import com.binhgiunhiet_g3.utils.date;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dungd
 */
public class khuyenmaiview extends javax.swing.JPanel {
KhuyenMaiService khuyenMaiService = new KhuyenMaiServiceImpl();
    DefaultTableModel model = new DefaultTableModel();
    List<KhuyenMai> khuyenMais = new ArrayList<>();
  
    public khuyenmaiview() {
        initComponents();
        loadTableKhuyenMai(khuyenMaiService.getAll());
    }
       private void loadTableKhuyenMai(List<KhuyenMai> list) {
        this.model = (DefaultTableModel) tbl_khuyenmai.getModel();
        model.setRowCount(0);
        int i = 1;
        for (KhuyenMai khuyenMai : list) {
            model.addRow(new Object[]{i++, khuyenMai.getId(),
                khuyenMai.getMa(), khuyenMai.getGiaTri(), khuyenMai.getNgayBatDau(), khuyenMai.getNgayKetThuc(), khuyenMai.getKieuGiamGia() == 0 ? "Phần Trăm" : "Tiền Mặt", khuyenMai.getTrangThai() == 0 ? "Đang Hoạt Động" : "Dừng Hoạt Động"
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        rdo_phantram = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        rdo_ngunghoatdong = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        txt_ma = new javax.swing.JTextField();
        txt_giatri = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        tbn_upadate = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tbn_clean = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_khuyenmai = new javax.swing.JTable();
        txt_ngayketthuc = new com.toedter.calendar.JDateChooser();
        txt_ngaybatdau = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        rdo_tienmat = new javax.swing.JRadioButton();
        rdo_danghoatdong = new javax.swing.JRadioButton();

        buttonGroup1.add(rdo_phantram);
        rdo_phantram.setSelected(true);
        rdo_phantram.setText("Phần Trăm");

        jLabel13.setText("Kiểu Giảm Giá");

        buttonGroup2.add(rdo_ngunghoatdong);
        rdo_ngunghoatdong.setText("Ngừng Hoạt Động");

        jLabel14.setText("Trạng Thái");

        txt_ma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maActionPerformed(evt);
            }
        });

        jButton1.setText("Lưu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Hóa Đơn", "Tên Sản Phẩm", "Loại", "Màu Sắc", "Chất Liệu", "Giảm Giá", "Số Lượng", "Giá Bán", "Trạng Thái"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        tbn_upadate.setText("Cập Nhật");
        tbn_upadate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_upadateActionPerformed(evt);
            }
        });

        jLabel15.setText("Giá Trị");

        jLabel11.setText("Ngày Bắt Đầu");

        jLabel12.setText("Ngày Kết Thúc");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(24, 24, 24)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        tbn_clean.setText("Mới");
        tbn_clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_cleanActionPerformed(evt);
            }
        });

        tbl_khuyenmai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Id", "Mã Khuyến Mãi", "Giá Trị", "Ngày Bắt Đầu", "Ngày Kết Thúc", "Kiểu Giảm Giá", "Trạng Thái"
            }
        ));
        tbl_khuyenmai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_khuyenmaiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_khuyenmai);

        jLabel10.setText("Mã Khuyến Mại");

        buttonGroup1.add(rdo_tienmat);
        rdo_tienmat.setText("Tiền Mặt");

        buttonGroup2.add(rdo_danghoatdong);
        rdo_danghoatdong.setSelected(true);
        rdo_danghoatdong.setText("Đang Hoạt Động");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel13))
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdo_danghoatdong, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdo_ngunghoatdong, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_giatri, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ma, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ngaybatdau, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ngayketthuc, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdo_phantram, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdo_tienmat, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(tbn_upadate, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(tbn_clean, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_giatri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_ngaybatdau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_ngayketthuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdo_phantram)
                                    .addComponent(rdo_tienmat))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(rdo_danghoatdong)
                            .addComponent(rdo_ngunghoatdong))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tbn_upadate, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(tbn_clean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_maActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        khuyenMaiService.add(getKhuyenMai());
        JOptionPane.showMessageDialog(this, "Thêm thành công");
        loadTableKhuyenMai(khuyenMaiService.getAll());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbn_upadateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_upadateActionPerformed
        // TODO add your handling code here: int row = tbl_khuyenmai.getSelectedRow();
        int row = tbl_khuyenmai.getSelectedRow();
        KhuyenMai km = getKhuyenMai();
        if (km == null) {
            return;
        }
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn dữ liệu");
            return;
        }
        Object value = tbl_khuyenmai.getValueAt(row, 1);
        if (value == null) {
            JOptionPane.showMessageDialog(this, "Dữ liệu không hợp lệ");
            return;
        }
        String ma = value.toString();
        try {
            int id = Integer.parseInt(ma);
            khuyenMaiService.update(km, id);
            JOptionPane.showMessageDialog(this, "Sửa thành công");
            loadTableKhuyenMai(khuyenMaiService.getAll());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Không thể chuyển đổi thành số nguyên");
            e.printStackTrace();
        }
    }//GEN-LAST:event_tbn_upadateActionPerformed

    private void tbn_cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_cleanActionPerformed
        // TODO add your handling code here:
        this.clearFrom();
    }//GEN-LAST:event_tbn_cleanActionPerformed

    private void tbl_khuyenmaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_khuyenmaiMouseClicked
        // TODO add your handling code here:
        int index = tbl_khuyenmai.getSelectedRow();
        txt_ma.setText(tbl_khuyenmai.getValueAt(index, 2).toString());
        txt_giatri.setText(tbl_khuyenmai.getValueAt(index, 3).toString());
        txt_ngaybatdau.setDate(date.toDate(tbl_khuyenmai.getValueAt(index, 4).toString()));
        txt_ngayketthuc.setDate(date.toDate(tbl_khuyenmai.getValueAt(index, 5).toString()));
        if (tbl_khuyenmai.getValueAt(index, 6).toString().equalsIgnoreCase("Phần Trăm")) {
            rdo_phantram.setSelected(true);
        } else {
            rdo_tienmat.setSelected(true);
        }
        if (tbl_khuyenmai.getValueAt(index, 7).toString().equalsIgnoreCase("Đang Hoạt Động")) {
            rdo_danghoatdong.setSelected(true);
        } else {
            rdo_ngunghoatdong.setSelected(true);
        }
    }//GEN-LAST:event_tbl_khuyenmaiMouseClicked

private KhuyenMai getKhuyenMai() {
        KhuyenMai khuyenMai = new KhuyenMai();
        khuyenMai.setMa(txt_ma.getText());
        khuyenMai.setNgayBatDau(txt_ngaybatdau.getDate());
        khuyenMai.setNgayKetThuc(txt_ngaybatdau.getDate());
        khuyenMai.setGiaTri(Integer.parseInt(txt_giatri.getText()));
        if (rdo_phantram.isSelected()) {
            khuyenMai.setKieuGiamGia(0);
        } else {
            khuyenMai.setKieuGiamGia(1);
        }
        if (rdo_danghoatdong.isSelected()) {
            khuyenMai.setTrangThai(0);
        } else {
            khuyenMai.setTrangThai(1);
        }
        
        return khuyenMai;
    }

    private void clearFrom() {
        txt_ma.setText(null);
        txt_giatri.setText(null);
        txt_ngaybatdau.setDate(null);
        txt_ngayketthuc.setDate(null);
        rdo_danghoatdong.setSelected(false);
        rdo_phantram.setSelected(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JRadioButton rdo_danghoatdong;
    private javax.swing.JRadioButton rdo_ngunghoatdong;
    private javax.swing.JRadioButton rdo_phantram;
    private javax.swing.JRadioButton rdo_tienmat;
    private javax.swing.JTable tbl_khuyenmai;
    private javax.swing.JButton tbn_clean;
    private javax.swing.JButton tbn_upadate;
    private javax.swing.JTextField txt_giatri;
    private javax.swing.JTextField txt_ma;
    private com.toedter.calendar.JDateChooser txt_ngaybatdau;
    private com.toedter.calendar.JDateChooser txt_ngayketthuc;
    // End of variables declaration//GEN-END:variables
}
